# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 70a5a50bdd209efe502bc7c61d2840c4bb6359775dea25ed3d4038aad318f49df9600f2f58658b769618c3627e5a0f95c2f02c01bc8627d0f102b28173ebdaf2

test:
  secret_key_base: 366772cacd7b0bed9c14b435b1dac01b007ae2271513b9d1cb96c43e34d44ca36fe1cf68937fba6f7afcfd08df7b3af681c73f95bbd67803cabb2ec03aa244c3

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
